acercade
CarlosPn/Euphoria-Garden pull request #4
Opened 2020-04-16 00:02 UTC by carlosloarca

Se  creo  el contenido de  tipografia  de  "Acerca de  nosotros,  y  filosofía de la empresa"

2020-04-16 00:10 UTC, Lulzphantom requested changes

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestra misión</h6> -->
Tratar de no enviar comentarios de código innecesario a master, que los comentarios sean para descripciones y documentación.

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +        <!-- <a href="#" class="card-link">Card link</a>
Otro por acá

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestra visión</h6> -->
Acá otro

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +      <a href="#" class="card-link">Another link</a> -->
👀

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestro Objetivo</h6> -->
👀 ...

2020-04-16 00:10 UTC, Lulzphantom commented on views/nosotros.html
> +
El contenido de la pagina esta fuera de su etiqueta body 💥

2020-04-17 00:38 UTC, merged

2020-04-17 00:48 UTC, carlosloarca commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestra misión</h6> -->
Vale , gracias!

2020-04-17 00:48 UTC, carlosloarca commented on views/nosotros.html
> +        <!-- <a href="#" class="card-link">Card link</a>
OK

2020-04-17 00:48 UTC, carlosloarca commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestra visión</h6> -->
OK

2020-04-17 00:49 UTC, carlosloarca commented on views/nosotros.html
> +      <a href="#" class="card-link">Another link</a> -->
OK

2020-04-17 00:49 UTC, carlosloarca commented on views/nosotros.html
> +        <!-- <h6 class="card-subtitle mb-2 text-muted">Nuestro Objetivo</h6> -->
OK

2020-04-17 00:49 UTC, carlosloarca commented on views/nosotros.html
> +
OK